import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xassha David | Front-End Developer</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

    </div>
  )
}
